version: '3.5'
services:
  unga:
    build: .
    container_name: unevergamealone
    restart: unless-stopped
    environment:
      - JWT_TOKEN=${JWT_TOKEN}
      - DB_NAME=${DB_NAME}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - TZ=Europe/Berlin
    volumes:
      - ./images:/app/public/images/upload':rw
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080